/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bunty_example_NativeExample */

#ifndef _Included_com_bunty_example_NativeExample
#define _Included_com_bunty_example_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bunty_example_NativeExample
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bunty_example_NativeExample_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
